### ISSUE TITLE
implement gettxout API call

### ISSUE THREAD

**Issue by cipig** [rubycoinorg/rubycoin#8]
I would like to integrate Rubycoin in BarterDEX, a decentralized exchange based on atomic swaps. Unfortunately the wallet is missing the gettxout API call.
https://bitcoin.org/en/developer-reference#gettxout
https://chainquery.com/bitcoin-api/gettxout
Could this be implemented?

**Comment by FuzzyHobbit** [comment]
This API call will be available when the upgrade to Bitcoin v0.16 is complete.
